# Define stages for the CI/CD pipeline
stages:
  - build_docker_image

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:eard-${CI_COMMIT_SHORT_SHA}

build-eard:
  image: docker

  services:
    - docker:dind

  stage: build_docker_image

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker build -t ${CONTAINER_IMAGE} Dockerfile --no-cache .
    - docker push ${CONTAINER_IMAGE}
    - docker rmi ${CONTAINER_IMAGE}
    - docker logout $CI_REGISTRY
