[package]
name = "eard-libperegrine-stub"
version = "0.1.0"
authors = ["Dan Sheppard <dan@ebi.ac.uk>"]
edition = "2018"

[dependencies]
serde="*"
serde_derive="*"
ordered-float="*"

[dependencies.eard-interp]
version="*"
path="../../eard/interp"
