[package]
name = "eard-compiler-libperegrine"
version = "0.0.0"
authors = ["ensembl-webteam@ebi.ac.uk"]
edition = "2018"

[dependencies]
anyhow="*"
clap = { version = "4", features = ["derive"] }

[dependencies.eard-compiler-lib]
path = "../compiler-lib"
